#!/bin/bash
#
# Copyright 2014 Andrew Schwartzmeyer

set -o errexit -o nounset

hash=$(echo "$@" | sha1sum | awk '{print $1}')
lockfile="/tmp/$hash.lock"

if [ ! -e $lockfile ]; then
    trap "rm -f $lockfile; exit" INT TERM EXIT
    touch $lockfile
    eval "$@"
    rm $lockfile
    trap - INT TERM EXIT
else
    echo "$@ is already running"
    exit
fi
