#!/bin/bash
set -o errexit -o nounset

if (hash pmset 2>/dev/null && hash caffeinate 2>/dev/null); then
    if (pmset -g ps | grep AC); then
	caffeinate -s "$@"
    else
	echo "$@ would run if not on battery power"
      	exit
    fi
else 
    eval $@
fi
