#!/bin/bash
# Copyright 2014 Andrew Schwartzmeyer
set -u

cd ~
if [[ ! -e ~/.ssh/id_rsa.pub ]]; then
    ssh-keygen
    cat .ssh/id_rsa.pub
    read -p "Add SSH keys where needed! Press any key to continue... " -n1 -s
else
    echo "SSH key already exists, continuing..."
fi

git clone git@github.com:andschwa/bin.git
./bin/vcsh clone git@suchcodemuchlove.com:dotfiles/mr.git

echo "Pulling in dotfiles..."
[[ -e ~/.bashrc ]] && mv ~/.bashrc ~/.bashrc.orig
./bin/mr checkout
./bin/vcsh run mr git update-index --assume-unchanged LICENSE README.org
rm LICENSE README.org

echo "Dotfiles setup! Reload session to contine..."
