#!/bin/bash
lockfile=~/.duply/verify.lock
export PATH=/usr/local/bin:$PATH
ulimit -n 1024

if [ ! -e $lockfile ]; then
    trap "rm -f $lockfile; exit" INT TERM EXIT
    touch $lockfile
    duply slartibartfast verify_purge --force
    duply krikkit verify_purge --force
    rm $lockfile
    trap - INT TERM EXIT
else
    echo "duply-backup $1 is already running"
fi
