#!/bin/bash
lockfile=~/.duply/$1.lock
export PATH=/usr/local/bin:$PATH
ulimit -n 1024
source ~/.backuppass

if [ ! -e $lockfile ]; then
    trap "rm -f $lockfile; exit" INT TERM EXIT
    touch $lockfile
    if (which pmset && which caffeinate); then
	if (pmset -g ps | grep AC); then
	    caffeinate -s nice duply "$1" backup
	fi
    else
	nice duply "$1" backup
    fi
    rm $lockfile
    trap - INT TERM EXIT
else
    echo "duply-backup $1 is already running"
fi
