* Andrew Schwartzmeyer's dotfiles
** bootstrap
#+begin_src sh
  curl https://suchcodemuchlove.com/dotfiles/bin/raw/master/dotfiles > bootstrap && bash bootstrap
#+end_src
** myrepos and vcsh
I use [[http://myrepos.branchable.com/][myrepos]] in conjunction with
[[https://github.com/RichiH/vcsh][vcsh]] to fully automate the syncing
and version control of my various dotfile repositories.

With the =mr= (myrepos) configuration files in =~/.mr/repos-enabled=,
the command =mr checkout= (after cloning this repository to =~/.mr=)
will automatically clone my:

- [[https://github.com/andschwa/bin][scripts (~/bin)]] scripts
- [[http://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration][git]] configuration
- [[https://github.com/nojhan/liquidprompt][liquidprompt]] shell theme
- [[https://github.com/andschwa/shell][shell]] configuration
- [[https://github.com/sorin-ionescu/prezto/][prezto]] zsh modules

Enabling non-default repositories is as simple as symlinking:
#+begin_src sh
  cd ~/.mr/repos-enabled
  ln -s ../repos-available/emacs.conf .
#+end_src

- [[https://github.com/cask/cask][Cask]] Emacs package manager
- crontabs
- [[http://duply.net/][duply]] backup profiles
- [[https://github.com/andschwa/emacs][Emacs]] configuration
- [[https://github.com/lra/mackup][mackup]] OS X app settings using
- [[http://offlineimap.org/][offlinemap]] settings
- [[https://github.com/sstephenson/rbenv][rbenv]] Ruby version manager
- [[http://sieve.info/][sieve]] mail filters
- [[http://tmux.sourceforge.net/][tmux]] configuration with [[https://github.com/tmux-plugins/tpm][tpm]]


The repositories that track bare files which belong in =$HOME= (such
as =git= and =shell=), are all "cloned" into =$HOME= concurrently. The
magic that makes this happen is =vcsh=, which bare clones the
repositores to =~/.config/vcsh/repos.d= and sets their (shared)
working directory to =$HOME=. Version control access to the different
repositories is then delegated to =vcsh=, such as =vcsh foo status= or
=vcsh bar diff=, which allows full use of git (or any other myrepos
supported VCS). In this way, files that belong to different
repositories (such as =~/.gitconfig= and =~/.zshrc=) can happily
coexist (without being symlinked!) in the same directory.

** license
Except where otherwise noted (e.g. cronic, duply, mr, and vcsh),
scripts (and other code) are written and licensed by me, Andrew
Schwartzmeyer, under the provided AGPLv3 License.
