# Setup environment
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    export PATH="~/bin:/usr/local/bin:$PATH:."
elif [[ "$OSTYPE" == darwin* ]]; then
    export PATH="~/bin:/usr/local/bin:$PATH:."
fi

ZSH="$HOME/.oh-my-zsh"
TERM="xterm-256color"
DISABLE_AUTO_UPDATE=true
ZSH_THEME="sorin"
EDITOR="emacsclient -c"

source ~/.fresh/build/shell.sh
source $ZSH/oh-my-zsh.sh

# Zsh configuration
limit coredumpsize 0
setopt menu_complete
setopt no_beep

# boxen
# [ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh
