# Setup environment
export PATH="~/bin:/usr/local/bin:$PATH:/usr/local/share/python3:/usr/local/share/python:/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems:/usr/local/share/npm/bin:."
ZSH="$HOME/.oh-my-zsh" # Point to location of oh-my-zsh
TERM="xterm-256color" # Fixes color issues
ZSH_THEME="agnoster_beta"
ZSH_TMUX_AUTOSTART=true
DEFAULT_USER="andrew" # Used for agnoster
EDITOR="vim"

source ~/.fresh/build/shell.sh
source $ZSH/oh-my-zsh.sh

# Zsh configuration
limit coredumpsize 0
setopt menu_complete
setopt no_beep
