# Setup environment
ZSH="$HOME/.oh-my-zsh" # Point to location of oh-my-zsh
PATH="/usr/local/bin:/usr/local/share/python:$PATH:."
TERM="xterm-256color" # Fixes color issues
ZSH_THEME=""
MY_ZSH_THEME=$ZSH_THEME
DEFAULT_USER="andrew" # Used for agnoster
EDITOR="vim"

source ~/.fresh/build/shell.sh
source $ZSH/oh-my-zsh.sh
source "/Users/andrew/Code/agnoster/agnoster.zsh-theme"

# Zsh configuration
limit coredumpsize 0
setopt menu_complete
setopt no_beep
